### ISSUE TITLE
Setup Google Crawl

### ISSUE THREAD

**Issue by tmiles2** [emory-libraries/blacklight-launch#24]

**Comment by tmiles2** [comment]
We've identified the requirements/ confirmation needs but we holding on to implementation until the work is largely done.

**Comment by tmiles2** [comment]
Doug and Emily will discuss this ticket.

**Comment by eporter23** [comment]
We need to go to google webmaster tools to configure a new site property if we want to monitor how it is being crawled. That said, it appears to already have been crawled since we had incoming links to it already from various banners and website announcements. 

![Screen Shot 2021-11-22 at 11.39.20 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/e6156a51-3224-4675-9e15-a3b21d754ed1)
